### ISSUE TITLE
how to fix this?

### ISSUE THREAD

**Issue by Mike129812** [rickoooooo/RDPwnFinder#5]
Running ubuntu 18.04 and getting this error
root@james:~/RDPwnFinder# sudo python scripts/RDPwnFinder.py -n models/ADABoostClassifier.mdl -g images/gray -c images/color -p hacked 200.55.216.216
Traceback (most recent call last):
  File "scripts/RDPwnFinder.py", line 363, in <module>
    main(width, height, ssColorPath, ssGrayPath, pwnedPath, timeout, targetFile, trainingModel, args)
  File "scripts/RDPwnFinder.py", line 269, in main
    classifier = load(trainingModel)
  File "/usr/lib/python2.7/dist-packages/joblib/numpy_pickle.py", line 459, in load
    obj = unpickler.load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1096, in load_global
    klass = self.find_class(module, name)
  File "/usr/lib/python2.7/pickle.py", line 1132, in find_class
    klass = getattr(mod, name)
AttributeError: 'module' object has no attribute 'NumpyArrayWrapper'

also could you make a requirements.txt file so that it would be easier to install all essential tools

**Comment by James94665** [comment]
Just use kali linux, comes with most of the packages installed

**Comment by rickoooooo** [comment]
I'll see if I can get something together to make it easier to install required packages.

**Comment by Mike129812** [comment]
Thanks :)
